INSERT INTO mpa_rating (name)
SELECT 'G' WHERE NOT EXISTS (SELECT 1 FROM mpa_rating WHERE name = 'G')
UNION ALL
SELECT 'PG' WHERE NOT EXISTS (SELECT 1 FROM mpa_rating WHERE name = 'PG')
UNION ALL
SELECT 'PG-13' WHERE NOT EXISTS (SELECT 1 FROM mpa_rating WHERE name = 'PG-13')
UNION ALL
SELECT 'R' WHERE NOT EXISTS (SELECT 1 FROM mpa_rating WHERE name = 'R')
UNION ALL
SELECT 'NC-17' WHERE NOT EXISTS (SELECT 1 FROM mpa_rating WHERE name = 'NC-17');

INSERT INTO genre (name)
SELECT 'Drama' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE name = 'Drama')
UNION ALL
SELECT 'Comedy' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE name = 'Comedy')
UNION ALL
SELECT 'Adventure' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE name = 'Adventure')
UNION ALL
SELECT 'Sci‑Fi' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE name = 'Sci‑Fi')
UNION ALL
SELECT 'Fantasy' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE name = 'Fantasy')
UNION ALL
SELECT 'Horror' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE name = 'Horror')
UNION ALL
SELECT 'Mystery' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE name = 'Mystery')
UNION ALL
SELECT 'Action' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE name = 'Action')
UNION ALL
SELECT 'Musical' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE name = 'Musical')
UNION ALL
SELECT 'Western' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE name = 'Western')
UNION ALL
SELECT 'Thriller' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE name = 'Thriller');